package homeassistant

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func RenderPackage() []byte {
	return []byte(`# Generated by Home Sentinel. This file contains no credentials.
group:
  home_sentinel_status:
    name: Home Sentinel
    entities:
      - sensor.home_sentinel_system_health
      - sensor.home_sentinel_recording_disk_free
      - sensor.home_sentinel_ai_status
      - sensor.home_sentinel_backup_status
`)
}

func RenderDashboard(cameraEntityIDs []string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Generated by Home Sentinel. Use with Home Assistant YAML-mode Lovelace dashboards.\n")
	b.WriteString("title: Home Sentinel\nviews:\n  - title: Security\n    path: sentinel\n    icon: mdi:shield-home\n    cards:\n      - type: entities\n        title: System\n        entities:\n          - sensor.home_sentinel_system_health\n          - sensor.home_sentinel_recording_disk_free\n          - sensor.home_sentinel_ai_status\n          - sensor.home_sentinel_backup_status\n")
	for _, id := range cameraEntityIDs {
		if !entityIDPattern.MatchString(id) || !strings.HasPrefix(id, "camera.") {
			return nil, fmt.Errorf("invalid camera entity id %q", id)
		}
		b.WriteString("      - type: picture-entity\n        entity: " + id + "\n        camera_view: live\n        show_name: true\n        show_state: false\n")
	}
	return []byte(b.String()), nil
}

func WriteGeneratedAssets(dir string, cameraEntityIDs []string) error {
	dashboard, err := RenderDashboard(cameraEntityIDs)
	if err != nil {
		return err
	}
	pkgDir := filepath.Join(dir, "packages")
	dashDir := filepath.Join(dir, "dashboards")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(dashDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "sentinel.yaml"), RenderPackage(), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dashDir, "sentinel.yaml"), dashboard, 0o644)
}
