package firewall

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/netip"
	"sort"
	"strconv"
	"strings"
)

// Policy describes only Home Sentinel-owned exposure. It deliberately does not
// replace the host's global firewall policy, so SSH/VPN administration remains
// under the operator's existing firewall.
type Policy struct {
	TrustedCIDRs        []string `json:"trusted_cidrs"`
	CameraCIDRs         []string `json:"camera_cidrs"`
	CameraEgressCIDRs   []string `json:"camera_egress_cidrs"`
	SentinelPort        uint16   `json:"sentinel_port"`
	WebRTCPort          uint16   `json:"webrtc_port"`
	EnforceCameraEgress bool     `json:"enforce_camera_egress"`
}

type MatrixRule struct {
	Source      string `json:"source"`
	Destination string `json:"destination"`
	Ports       string `json:"ports"`
	Action      string `json:"action"`
	Reason      string `json:"reason"`
}

func DefaultPolicy() Policy {
	return Policy{SentinelPort: 8080, WebRTCPort: 8555}
}

func ParseJSON(b []byte) (Policy, error) {
	p := DefaultPolicy()
	dec := json.NewDecoder(strings.NewReader(string(b)))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&p); err != nil {
		return Policy{}, err
	}
	if err := p.Validate(); err != nil {
		return Policy{}, err
	}
	return p, nil
}

func (p Policy) Validate() error {
	if p.SentinelPort == 0 || p.WebRTCPort == 0 {
		return errors.New("sentinel and WebRTC ports must be non-zero")
	}
	if len(p.TrustedCIDRs) == 0 {
		return errors.New("at least one trusted CIDR required")
	}
	if len(p.CameraCIDRs) == 0 {
		return errors.New("at least one camera CIDR required")
	}
	for name, values := range map[string][]string{"trusted": p.TrustedCIDRs, "camera": p.CameraCIDRs, "camera_egress": p.CameraEgressCIDRs} {
		for _, raw := range values {
			pr, err := netip.ParsePrefix(strings.TrimSpace(raw))
			if err != nil {
				return fmt.Errorf("%s CIDR %q: %w", name, raw, err)
			}
			if !pr.Addr().IsValid() {
				return fmt.Errorf("%s CIDR %q invalid", name, raw)
			}
		}
	}
	if p.EnforceCameraEgress && len(p.CameraEgressCIDRs) == 0 {
		return errors.New("camera_egress_cidrs required when enforce_camera_egress=true")
	}
	return nil
}

func normalize(values []string, v6 bool) []string {
	out := make([]string, 0, len(values))
	seen := map[string]bool{}
	for _, raw := range values {
		pr, err := netip.ParsePrefix(strings.TrimSpace(raw))
		if err != nil {
			continue
		}
		if pr.Addr().Is6() != v6 {
			continue
		}
		s := pr.Masked().String()
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}

func setDef(name, typ string, elems []string) string {
	if len(elems) == 0 {
		return ""
	}
	return fmt.Sprintf("    set %s { type %s; flags interval; elements = { %s } }\n", name, typ, strings.Join(elems, ", "))
}

// RenderNFT returns a self-contained nftables table. The input hook uses policy
// accept and only rejects access to Sentinel-owned published ports from
// untrusted networks. The forward hook can optionally constrain the dedicated
// Docker camera-egress subnet to configured camera networks.
func RenderNFT(p Policy) (string, error) {
	if err := p.Validate(); err != nil {
		return "", err
	}
	t4, t6 := normalize(p.TrustedCIDRs, false), normalize(p.TrustedCIDRs, true)
	c4, c6 := normalize(p.CameraCIDRs, false), normalize(p.CameraCIDRs, true)
	e4, e6 := normalize(p.CameraEgressCIDRs, false), normalize(p.CameraEgressCIDRs, true)
	var b strings.Builder
	b.WriteString("# Generated by Home Sentinel. Validate with: nft -c -f <file>\n")
	b.WriteString("table inet home_sentinel {\n")
	b.WriteString(setDef("trusted_v4", "ipv4_addr", t4))
	b.WriteString(setDef("trusted_v6", "ipv6_addr", t6))
	b.WriteString(setDef("camera_v4", "ipv4_addr", c4))
	b.WriteString(setDef("camera_v6", "ipv6_addr", c6))
	b.WriteString(setDef("camera_egress_v4", "ipv4_addr", e4))
	b.WriteString(setDef("camera_egress_v6", "ipv6_addr", e6))
	b.WriteString("    chain input {\n        type filter hook input priority -5; policy accept;\n")
	ports := strconv.Itoa(int(p.SentinelPort)) + ", " + strconv.Itoa(int(p.WebRTCPort))
	if len(t4) > 0 {
		fmt.Fprintf(&b, "        meta nfproto ipv4 tcp dport { %s } ip saddr != @trusted_v4 reject with tcp reset\n", ports)
		fmt.Fprintf(&b, "        meta nfproto ipv4 udp dport %d ip saddr != @trusted_v4 reject\n", p.WebRTCPort)
	}
	if len(t6) > 0 {
		fmt.Fprintf(&b, "        meta nfproto ipv6 tcp dport { %s } ip6 saddr != @trusted_v6 reject with tcp reset\n", ports)
		fmt.Fprintf(&b, "        meta nfproto ipv6 udp dport %d ip6 saddr != @trusted_v6 reject\n", p.WebRTCPort)
	}
	b.WriteString("    }\n")
	if p.EnforceCameraEgress {
		b.WriteString("    chain forward {\n        type filter hook forward priority -5; policy accept;\n")
		if len(e4) > 0 && len(c4) > 0 {
			b.WriteString("        meta nfproto ipv4 ip saddr @camera_egress_v4 ip daddr != @camera_v4 reject\n")
		}
		if len(e6) > 0 && len(c6) > 0 {
			b.WriteString("        meta nfproto ipv6 ip6 saddr @camera_egress_v6 ip6 daddr != @camera_v6 reject\n")
		}
		b.WriteString("    }\n")
	}
	b.WriteString("}\n")
	return b.String(), nil
}

func Matrix(p Policy) ([]MatrixRule, error) {
	if err := p.Validate(); err != nil {
		return nil, err
	}
	out := []MatrixRule{
		{"trusted LAN/VPN", "Sentinel UI/API", fmt.Sprintf("tcp/%d", p.SentinelPort), "ALLOW", "authenticated management plane"},
		{"untrusted/WAN", "Sentinel UI/API", fmt.Sprintf("tcp/%d", p.SentinelPort), "DENY", "management is never public by default"},
		{"trusted LAN/VPN", "go2rtc WebRTC media", fmt.Sprintf("tcp+udp/%d", p.WebRTCPort), "ALLOW", "managed live media"},
		{"untrusted/WAN", "go2rtc WebRTC media", fmt.Sprintf("tcp+udp/%d", p.WebRTCPort), "DENY", "media plane restricted to trusted networks"},
		{"any external", "MQTT/go2rtc API/Ollama/Frigate internal API", "1883,1984,11434,5000", "DENY", "ports must not be host-published"},
		{"Sentinel/Frigate camera-egress", "configured camera CIDRs", "RTSP/ONVIF/vendor", "ALLOW", "camera acquisition/probing"},
	}
	if p.EnforceCameraEgress {
		out = append(out, MatrixRule{"Sentinel/Frigate camera-egress", "all non-camera destinations", "any", "DENY", "camera plane cannot become general WAN egress"})
	}
	return out, nil
}
